name: Comments Commands
on:
    issue_comment:
        types: [created, edited, deleted]
jobs:
    diff:
        name: Diff
        runs-on: ubuntu-latest
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/diff') }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install Dependencies
                run: |
                    npm ci

            -   name: Diff
                uses: youyo/aws-cdk-github-actions@v2
                with:
                    cdk_subcommand: 'diff'
                    cdk_args: '--require-approval never'
                    actions_comment: true
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    AWS_DEFAULT_REGION: 'us-west-2'
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    STAGE: 'test'
